# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vlog -work work +define+COCOTB_SIM -sv -timescale 1ns/1ps -mfcu +acc  D:/Project_lib/src/cfg/sys_cfg_wrap.v D:/Project_lib/src/reg/sys_cfg_regs.v D:/Project_lib/src/reg/cfg_reg.v
vsim -g ADDR_WIDTH=32 -g DATA_WIDTH=32 -g BYTE_NUM=4 -onfinish exit -pli D:/software/miniconda/lib/site-packages/cocotb/libs/cocotbvpi_modelsim.dll   sim_build/work.sys_cfg_wrap
onbreak resume
run -all
quit
