######################################################################
#
# File name : test_top_wave.do
# Created on: Sun Sep 12 15:51:11 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
