######################################################################
#
# File name : test_top_simulate.do
# Created on: Wed Sep 15 20:54:01 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L ten_gig_eth_mac_v15_1_6 -L xil_defaultlib -L ten_gig_eth_pcs_pma_v6_0_14 -L xlconstant_v1_1_5 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.test_top xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {test_top_wave.do}

view wave
view structure
view signals

log -r /*

do {test_top.udo}

run 1000ns
