######################################################################
#
# File name : test_top_compile.do
# Created on: Wed Sep 15 20:53:55 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib
vlib modelsim_lib/msim/ten_gig_eth_pcs_pma_v6_0_14

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap ten_gig_eth_pcs_pma_v6_0_14 modelsim_lib/msim/ten_gig_eth_pcs_pma_v6_0_14

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../net_test.srcs/sources_1/ip/clk_wiz_0" \
"../../../../net_test.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/ten_gig_eth_mac_v15_1_1/hdl/bd_efdb_0_xmac_0_core.v" \
"../../../../net_test.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_0_xmac_0_sync_resetn.v" \
"../../../../net_test.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_0_xmac_0_block.v" \
"../../../../net_test.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_0_xmac_0.v" \

vlog -64 -incr -work ten_gig_eth_pcs_pma_v6_0_14  "+incdir+../../../../net_test.srcs/sources_1/ip/clk_wiz_0" \
"../../../../net_test.ip_user_files/ipstatic/hdl/ten_gig_eth_pcs_pma_v6_0_rfs.v" \

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../net_test.srcs/sources_1/ip/clk_wiz_0" \
"../../../../net_test.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_gtwizard_10gbaser_gt.v" \
"../../../../net_test.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_gtwizard_10gbaser_multi_gt.v" \
"../../../../net_test.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_ff_synchronizer_rst.v" \
"../../../../net_test.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_ff_synchronizer.v" \
"../../../../net_test.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_local_clock_and_reset.v" \
"../../../../net_test.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_sim_speedup_controller.v" \
"../../../../net_test.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_cable_pull_logic.v" \
"../../../../net_test.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_block.v" \
"../../../../net_test.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0.v" \
"../../../../net_test.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_2/sim/bd_efdb_0_prtad_driver_0.v" \
"../../../../net_test.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_3/sim/bd_efdb_0_dcm_locked_driver_0.v" \
"../../../../net_test.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_4/sim/bd_efdb_0_pma_pmd_type_driver_0.v" \
"../../../../net_test.ip_user_files/ip/axi_10g_ethernet_0/sim/axi_10g_ethernet_0.v" \
"../../../../net_test.ip_user_files/ip/vio_cfg/sim/vio_cfg.v" \
"../../../../net_test.ip_user_files/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../net_test.ip_user_files/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_axi_fifo.v" \
"../../../../net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_ff_synchronizer_rst2.v" \
"../../../../net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_fifo_block.v" \
"../../../../net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_fifo_ram.v" \
"../../../../net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_gt_common.v" \
"../../../../net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_shared_clock_and_reset.v" \
"../../../../net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_shared_clocking_wrapper.v" \
"../../../../net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_support.v" \
"../../../../net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_sync_block.v" \
"../../../../net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_sync_reset.v" \
"../../../../net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_xgmac_fifo.v" \
"../../../../net_test.srcs/sources_1/new/eth_ctrl.v" \
"../../../../net_test.srcs/sources_1/new/eth_fsm.v" \
"../../../../../../DESIGN/SRC/BASE/sig_pulse.v" \
"../../../../../../DESIGN/SRC/SIM/sim_clk_rst.v" \
"../../../../net_test.srcs/sources_1/new/test_axis_data_gen.v" \
"../../../../net_test.srcs/sources_1/new/test_axis_rx_gen.v" \
"../../../../net_test.srcs/sources_1/new/test_axis_tx_gen.v" \
"../../../../net_test.srcs/sources_1/new/test_cfg.v" \
"../../../../net_test.srcs/sources_1/new/top.v" \

vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../../net_test.srcs/sources_1/ip/clk_wiz_0" \
"../../../../net_test.srcs/sources_1/new/eth_cfg.v" \
"../../../../net_test.srcs/sources_1/new/eth_wrap.v" \
"../../../../net_test.srcs/sim_1/new/test_top.sv" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

