# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vlog -work work +define+COCOTB_SIM -sv -timescale 1ns/1ps -mfcu +acc  D:/Gitlib/test/cocotb/src/test_top.sv
vsim  -onfinish exit -pli D:/software/miniconda/lib/site-packages/cocotb/libs/cocotbvpi_modelsim.dll   sim_build/work.test_top
log -recursive /*
onbreak resume
run -all
quit
