# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/eth_cons.xdc

# XDC: new/timing.xdc

# IP: ip/axi_10g_ethernet_0/axi_10g_ethernet_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_10g_ethernet_0 || ORIG_REF_NAME==axi_10g_ethernet_0} -quiet] -quiet
