# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Project/1_prj/net/net_test/net_test.cache/wt [current_project]
set_property parent.project_path D:/Project/1_prj/net/net_test/net_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Project/1_prj/net/net_test/net_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/new/eth_cfg.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/new/eth_wrap.v
}
read_verilog -library xil_defaultlib {
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_axi_fifo.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_ff_synchronizer_rst2.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_fifo_block.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_fifo_ram.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_gt_common.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_shared_clock_and_reset.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_shared_clocking_wrapper.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_support.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_sync_block.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_sync_reset.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/imports/imports/axi_10g_ethernet_0_xgmac_fifo.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/new/eth_ctrl.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/new/eth_fsm.v
  D:/Project/2_src/base/sig_pulse.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/new/test_axis_data_gen.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/new/test_axis_rx_gen.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/new/test_axis_tx_gen.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/new/test_cfg.v
  D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/new/top.v
}
read_ip -quiet D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/ip/axi_10g_ethernet_0/axi_10g_ethernet_0.xci
set_property used_in_implementation false [get_files -all d:/Project/1_prj/net/net_test/net_test.srcs/sources_1/ip/axi_10g_ethernet_0/synth/axi_10g_ethernet_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/1_prj/net/net_test/net_test.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_0_xmac_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/1_prj/net/net_test/net_test.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_0_xmac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Project/1_prj/net/net_test/net_test.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_0_xmac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/1_prj/net/net_test/net_test.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Project/1_prj/net/net_test/net_test.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/1_prj/net/net_test/net_test.srcs/sources_1/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0.xdc]

read_ip -quiet D:/Project/1_prj/net/net_test/net_test.srcs/sources_1/ip/vio_cfg/vio_cfg.xci
set_property used_in_implementation false [get_files -all d:/Project/1_prj/net/net_test/net_test.srcs/sources_1/ip/vio_cfg/vio_cfg.xdc]
set_property used_in_implementation false [get_files -all d:/Project/1_prj/net/net_test/net_test.srcs/sources_1/ip/vio_cfg/vio_cfg_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Project/1_prj/net/net_test/net_test.srcs/constrs_1/new/eth_cons.xdc
set_property used_in_implementation false [get_files D:/Project/1_prj/net/net_test/net_test.srcs/constrs_1/new/eth_cons.xdc]

read_xdc D:/Project/1_prj/net/net_test/net_test.srcs/constrs_1/new/timing.xdc
set_property used_in_implementation false [get_files D:/Project/1_prj/net/net_test/net_test.srcs/constrs_1/new/timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
