######################################################################
#
# File name : axi_10g_ethernet_0_demo_tb_compile.do
# Created on: Wed Sep 15 18:37:33 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib
vlib modelsim_lib/msim/ten_gig_eth_pcs_pma_v6_0_14

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap ten_gig_eth_pcs_pma_v6_0_14 modelsim_lib/msim/ten_gig_eth_pcs_pma_v6_0_14

vlog -64 -incr -work xil_defaultlib  \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/ten_gig_eth_mac_v15_1_1/hdl/bd_efdb_0_xmac_0_core.v" \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_0_xmac_0_sync_resetn.v" \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_0_xmac_0_block.v" \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_0/synth/bd_efdb_0_xmac_0.v" \

vlog -64 -incr -work ten_gig_eth_pcs_pma_v6_0_14  \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ipstatic/hdl/ten_gig_eth_pcs_pma_v6_0_rfs.v" \

vlog -64 -incr -work xil_defaultlib  \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_gtwizard_10gbaser_gt.v" \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_gtwizard_10gbaser_multi_gt.v" \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_ff_synchronizer_rst.v" \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_ff_synchronizer.v" \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_local_clock_and_reset.v" \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_sim_speedup_controller.v" \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_cable_pull_logic.v" \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0_block.v" \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_1/synth/bd_efdb_0_xpcs_0.v" \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_2/sim/bd_efdb_0_prtad_driver_0.v" \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_3/sim/bd_efdb_0_dcm_locked_driver_0.v" \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/bd_0/ip/ip_4/sim/bd_efdb_0_pma_pmd_type_driver_0.v" \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/bd_0/sim/bd_efdb_0.v" \
"../../../../axi_10g_ethernet_0_ex.ip_user_files/ip/axi_10g_ethernet_0/sim/axi_10g_ethernet_0.v" \
"../../../../imports/axi_10g_ethernet_0_address_swap.v" \
"../../../../imports/axi_10g_ethernet_0_axi_fifo.v" \
"../../../../imports/axi_10g_ethernet_0_axi_lite_sm.v" \
"../../../../imports/axi_10g_ethernet_0_axi_mux.v" \
"../../../../imports/axi_10g_ethernet_0_axi_pat_check.v" \
"../../../../imports/axi_10g_ethernet_0_axi_pat_gen.v" \
"../../../../imports/axi_10g_ethernet_0_clocking.v" \
"../../../../imports/axi_10g_ethernet_0_example_design.v" \
"../../../../imports/axi_10g_ethernet_0_ff_synchronizer_rst2.v" \
"../../../../imports/axi_10g_ethernet_0_fifo_block.v" \
"../../../../imports/axi_10g_ethernet_0_fifo_ram.v" \
"../../../../imports/axi_10g_ethernet_0_gen_check_wrapper.v" \
"../../../../imports/axi_10g_ethernet_0_gt_common.v" \
"../../../../imports/axi_10g_ethernet_0_shared_clock_and_reset.v" \
"../../../../imports/axi_10g_ethernet_0_shared_clocking_wrapper.v" \
"../../../../imports/axi_10g_ethernet_0_support.v" \
"../../../../imports/axi_10g_ethernet_0_sync_block.v" \
"../../../../imports/axi_10g_ethernet_0_sync_reset.v" \
"../../../../imports/axi_10g_ethernet_0_xgmac_fifo.v" \
"../../../../imports/axi_10g_ethernet_0_demo_tb.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

