######################################################################
#
# File name : axi_10g_ethernet_0_demo_tb_wave.do
# Created on: Wed Sep 15 18:37:39 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
